In [1]:
import numpy as np, scipy, matplotlib
import matplotlib.pyplot as pl
from scipy.optimize import curve_fit
import matplotlib.ticker as ticker
from scipy.signal import detrend
import scipy.constants as const
%pylab

g031_freq, g031_temp = np.loadtxt("G031.727.dat", unpack = 1)

#Get the stupid frequencies in ascending order
g031_freq = g031_freq[:: -1] * 1e6
g031_temp = g031_temp[:: -1]

#Trim off the first 500 samples corresponding to bad baseline
g031_freq = g031_freq[300:]
g031_temp = g031_temp[300:]

#Script to remove baseline
#Use polyfit instead of curve_fit as don't know the function

coeff = np.polyfit(g031_freq, g031_temp, 3)
baseline = np.poly1d(coeff)

g031_temp_corr = g031_temp - baseline(g031_freq)

#pl.plot(g031_freq, g031_temp_corr)

#Fit that weak line towards the end of the spectrum:

def gaussian(x, a, b, c):
    
    return a * np.exp(-(x - b) ** 2 / (2 * c ** 2))

popt, pconv = curve_fit(gaussian, g031_freq[3100: 3300], g031_temp_corr[3100: 3300], p0 = (0.1, 9815e6, 1e6), maxfev = 2000)

print(popt)
print(np.diag(pconv) ** 2)

hpbw = popt[2] * 2.355 


Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib
[2.35659383e-03 9.81327447e+09 2.60862123e+05]
[1.11408487e-15 2.94682187e+17 2.96288046e+17]


/usr/local/lib/python2.7/dist-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['detrend']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [2]:
import numpy as np, scipy, matplotlib
import matplotlib.pyplot as pl
from scipy.optimize import curve_fit
import matplotlib.ticker as ticker
from scipy.signal import detrend
import scipy.constants as const
%matplotlib notebook

g034_freq, g034_temp = np.loadtxt("G034.133.dat", unpack = 1)

#Get the stupid frequencies in ascending order
g034_freq = g034_freq[:: -1] * 1e6
g034_temp = g034_temp[:: -1]

#Trim off the first 500 samples corresponding to bad baseline
g034_freq = g034_freq[500:]
g034_temp = g034_temp[500:]

#detrend the signal to bring it down to earth
g034_temp = detrend(g034_temp, type = 'constant')

#pl.plot(g034_freq[500: 1000], g034_temp[500: 1000])

#Script to fit a gaussian

def gaussian2(x, a, b, c):
    
    return a * np.exp(-(x - b) ** 2 / (2 * c ** 2))

popt2, pconv = curve_fit(gaussian2, g034_freq[500: 1000], g034_temp[500: 1000], p0 = (1, 9170e6, 2e6), maxfev = 2000)

print(popt)
print(np.diag(pconv) ** 2)

hpbw = popt[2] * 2.355 

[2.35659383e-03 9.81327447e+09 2.60862123e+05]
[2.03886234e-10 3.26041601e+16 3.27407220e+16]


In [3]:
fig, (ax0, ax1) = pl.subplots(nrows = 2, ncols = 1)

ax0.plot(g031_freq[3000: 3500], g031_temp[3000: 3500], color = 'r', label = 'data')
ax0.plot(g031_freq[3000: 3500], gaussian(g031_freq[3000: 3500], *popt), color = 'g', label = 'fit')

ax1.plot(g034_freq[500: 1000], g034_temp[500: 1000], color = 'r', label = 'data')
ax1.plot(g034_freq[500: 1000], gaussian2(g034_freq[500: 1000], *popt2), color = 'g', label = 'fit')

fig.text(0.00, 0.5, 'Antenna Temperature (K)', va='center', rotation='vertical', fontsize = 20)
ax1.set_xlabel("Frequency (Hz)", fontsize = 20)

fig.tight_layout()
ax0.legend(loc = 'best', frameon = False, fontsize = 15)
pl.show()